### ISSUE TITLE
Publish package to npm

### ISSUE THREAD

**Issue by aaccurso** [proyecto26/Phaser-Kinetic-Scrolling-Plugin#1]
Hi, could you publish this package to npm please?
I am using npm as a dependency manager and this would help me a lot.
It's really easy since you already have a package.json :) More info [here](https://docs.npmjs.com/cli/publish).
Great plugin by the way!
Thanks!

**Comment by jdnichollsc** [comment]
Ohh Excellent idea! Done! => https://www.npmjs.com/package/phaser-kinetic-scrolling-plugin
PD: Sorry for the delay... busy haha

**Comment by aaccurso** [comment]
Thanks a lot!
If you have the time you can do the same with bower, I know some people using it as a dependency manager as well.
You just need to do a `bower init`, followed by a `bower login` and finally `bower register phaser-kinetic-scrolling-plugin https://github.com/jdnichollsc/Phaser-Kinetic-Scrolling-Plugin.git`. More info [here](http://bower.io/docs/creating-packages/).
Cheers!

**Comment by jdnichollsc** [comment]
Done, sorry for the delay.
Bower i phaser-kinetic-scrolling-plugin
