### ISSUE TITLE
Multidirectional scrolling support

### ISSUE THREAD

**Issue by jorbascrumps** [proyecto26/Phaser-Kinetic-Scrolling-Plugin#10]
I know it's probably outside the scope of this project right now, but supporting multidirectional scrolling would be a nice feature to have. Currently scrollwheel support is enabled by setting either `verticalWheel` or `horizontalWheel` to `true`. However, setting both to `true` has some pretty unexpected behaviour, especially using a Macbook touchpad.

**Comment by jdnichollsc** [comment]
@iamchristopher The unexpected behaviour was fixed with the 1.0.6 version
