### ISSUE TITLE
Scrolling large bodies of text within a group

### ISSUE THREAD

**Issue by asciifaceman** [proyecto26/Phaser-Kinetic-Scrolling-Plugin#11]
I am wondering if this plugin would work for this use case.

I have a panel I made, say:
```
    // Tall panel
    var panelTall = this.game.add.bitmapData(250, 500);
    panelTall.ctx.fillStyle = '#5a6772';
    panelTall.ctx.strokeStyle = '#31363a';
    panelTall.ctx.lineWidth = 5;
    panelTall.ctx.fillRect(0, 0, 250, 500);
    panelTall.ctx.strokeRect(0, 0, 250, 500);
    this.game.cache.addBitmapData('panel', panelTall); 
```

And then I instantiate it in a group:

```
    this.stableGroup = this.game.add.group();
    this.stableGroup.position.setTo(25, 250);

    this.stableBody = this.stableGroup.addChild(this.game.add.image(0, 0, this.game.cache.getBitmapData('panel')));
```

Now within this I want to populate it with text objects vertically, and have it scrollable vertically at the borders roughly of the panel. Every comment thread seems to have you posting this library as an example but I can't seem to figure out how it would work like this.

**Comment by jdnichollsc** [comment]
Check the [current examples](https://github.com/jdnichollsc/Phaser-Kinetic-Scrolling-Plugin/tree/master/examples) please.
Regards, Nicholls

**Comment by asciifaceman** [comment]
Yes I have been all over the current examples. But if you just want to close this and wash your hands fine, but stop posting your plugin all over as the answer to this solution if you are unwilling to document its use properly.

**Comment by jdnichollsc** [comment]
If you want, you can see the code, learn about Phaser ([Camera](http://phaser.io/docs/2.6.2/Phaser.Camera.html), [fixedToCamera](http://phaser.io/docs/2.6.2/Phaser.Component.FixedToCamera.html)) and later improve the documentation with a Pull Request! ;)

**Comment by asciifaceman** [comment]
I was a little hasty with my pre-coffee monday morning reply. However I'm fairly familiar with Phaser and I wrote a window manager for it, however I Can't seem to understand how your work... works. Every example seems to be camera only and not moving objects. I can't for the life of me think of how to make my use case work, and that might just be how it is. 

I only want to scroll objects (like an infinite text list) not the entire camera.

**Comment by jdnichollsc** [comment]
Sorry, for the moment this plugin only works with the **camera**, but any contribution to the community is totally welcome 👍

**Comment by asciifaceman** [comment]
I might have to roll my own solution I guess then. With the knowledge you gained writing this, do you have any input on how to handle it?
