### ISSUE TITLE
Phaser CE 

### ISSUE THREAD

**Issue by JarLowrey** [proyecto26/Phaser-Kinetic-Scrolling-Plugin#15]
Since Phaser2 is no longer being maintained, the production dependency should be switched from phaser to phaser-ce

**Comment by jdnichollsc** [comment]
Let me test this plugin with Phaser-Ce, What's is that version?

**Comment by JarLowrey** [comment]
Phaser2 is no longer maintained, phaser-ce is the community edition of phaser2 that continues dev until phaser3 and lazer is ready. Phaser-ce is at 2.7.2 right now

**Comment by jdnichollsc** [comment]
Thanks for report this issue my friend!

**Comment by JarLowrey** [comment]
Sure, by the way I misspoke in previous comment. Lazer is now called Phaser3
