### ISSUE TITLE
select element

### ISSUE THREAD

**Issue by Ryuuke** [proyecto26/Phaser-Kinetic-Scrolling-Plugin#2]
Hello,
Nice plugin, but I'm encountering some troubles to select an element.
Say I wanna select a rectangle in your example, how can I achieve that ?

Thanks :)

Resolved : I did that by storing the mouse position when it's down, so when it's up I compare the new value with the old one, if it's the same position, I fire up the click event..

**Comment by jdnichollsc** [comment]
If you use sprites, you can use inputs.
