### ISSUE TITLE
stop slide effect after mouse click

### ISSUE THREAD

**Issue by Maeggi** [proyecto26/Phaser-Kinetic-Scrolling-Plugin#23]
hello,

can i stop slide effect after mouse click?
thank and sry, for my english.

**Comment by jdnichollsc** [comment]
Hi @Maeggi 
Please validate the changes of the example 3 https://github.com/jdnichollsc/Phaser-Kinetic-Scrolling-Plugin/blob/master/examples/js/example_3.js#L44
Regards, Nicholls
