### ISSUE TITLE
Auto scroll activated

### ISSUE THREAD

**Issue by Thaval** [proyecto26/Phaser-Kinetic-Scrolling-Plugin#25]
Hi,

I faced a bug I guess. When I enter a state and activate the kinematic scrolling plugin for the first time, everything is fine. When I leave the state and reenter it, the scrolling is activated which means the camera is scrolling although I haven't clicked yet.
Of course I call `this.game.kineticScrolling.stop();` when I shutdown the state.

**Comment by Thaval** [comment]
I fixed it by myself by adding 
`this.pressedDown = false;`
to the stop function.

**Comment by jdnichollsc** [comment]
Can you attach a demo please?

**Comment by Thaval** [comment]
I will when I find time. If not, remind me of that. But I dont need to, I come over that when I just looked through the source code.
Behaviour:
Click on a Phaser Button to enter a new state (let's call it simply S) and start the kinetic plugin. Then, when leaving the state S, again with a Phaser Button (it's always a click event), stop the kinetic plugin (care, pressedDown should still be true). Go back to state S by clicking the Phaser Button and as pressedDown is still true, the kinetic plugin is already active and consumes the click.

I'm trying to reproduce the problem whenever I find time. Currently I'm working on a long time thesis.

**Comment by jdnichollsc** [comment]
Fixed, thanks for the help!
