### ISSUE TITLE
Sprite shifts when game scale is not 1

### ISSUE THREAD

**Issue by microspace** [proyecto26/Phaser-Kinetic-Scrolling-Plugin#26]
When I set `scalefactor` to number other than 1, sprite starts to shift when I drag map around.
    
    this.game.world.scale.setTo(scalefactor, scalefactor);

![25](https://user-images.githubusercontent.com/2958584/52254914-06c22080-2932-11e9-9f39-cc8f656c122e.gif)

**Comment by jdnichollsc** [comment]
@microspace this looks an issue with the camera object of Phaser, this plugin only add a little mathematics to move that object
