### ISSUE TITLE
Disable body while dragging map around

### ISSUE THREAD

**Issue by microspace** [proyecto26/Phaser-Kinetic-Scrolling-Plugin#27]
Body is always following sprite in phaser. At low speed of map dragging it is not visible, but at higher speed body get compertely seperate from sprite. Sometimes body collided with game objects and false collision occures. **So is it possible to disable body when I drag map?**
(I can record video if issue is not clear from my description)

**Comment by jdnichollsc** [comment]
You can do that detecting if the camera is scrolling with `this.game.kineticScrolling.dragging` from the `update` method
