### ISSUE TITLE
Stopping plugin in inputDown event cause problem when plugin is started again

### ISSUE THREAD

**Issue by bongikairu** [proyecto26/Phaser-Kinetic-Scrolling-Plugin#4]
It's a rare case I guess. Chrome 46 on Mac.

Stopping plugin in inputDown event won't clean up plugin state. When plugin is started again, it start with dragging = true and things will move with cursor.

**Comment by jdnichollsc** [comment]
See please the new version to support Phaser 2.4.4, and now you can download it using Bower :)
